### ISSUE TITLE
create DB via Docker-compose

### ISSUE THREAD

**Issue by C4RN1V0R** [C4RN1V0R/dnd-navigator#1]
as the title says

**Comment by C4RN1V0R** [comment]
#1 must be done before

**Comment by mathiasstamm** [comment]
There's good information on [Posgresql's Docker-Hub](https://hub.docker.com/_/postgres) page. Do you already know what type of database you want to use?

Here's a snippet of Postgres' example `docker-compose.yml` file. Specifics will vary depending on the database you end up deciding on.
```yml
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
```
